# Use postgres/example user/password credentials
version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: websiteshot
      POSTGRES_USER: websiteshot
      POSTGRES_PASSWORD: websiteshot

  websiteshot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://websiteshot:websiteshot@db:5432/websiteshot
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://websiteshot:websiteshot@db:5432/websiteshot
    depends_on:
      - db

volumes:
  db:
