# Use postgres/example user/password credentials
version: "3.8"

volumes:
  database-data:

# networks:
#   stack:
#     name: stack
#     external: false

services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env

  websiteshot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    restart: always
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    depends_on:
      - database

  # Optional use of Prisma Studio. In production, comment out or remove the section below to prevent unwanted access to your database.
  # studio:
  #   restart: always
  #   networks:
  #     - stack
  #   ports:
  #     - 5556:5556
  #   env_file: .env
  #   environment:
  #     - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
  #   depends_on:
  #     - database
  #   command:
  #     - npx
  #     - prisma
  #     - studio
# END SECTION: Optional use of Prisma Studio.
